'use client'
import Link from 'next/link'
export default function TeethWhiteningContent() {
  return (
    <>
      <a href="#main" className="skip-link">Skip to main content</a>
      <div className="bg-wellness-dark text-white text-center py-2 text-sm" role="banner"><div className="max-w-site mx-auto px-4"><span className="opacity-80">Crisis support 24/7:</span>{' '}<a href="tel:988" className="font-medium hover:underline">Call 988</a></div></div>
      <nav className="bg-white sticky top-0 z-40 shadow-sm" aria-label="Main navigation"><div className="max-w-site mx-auto px-6 lg:px-12 py-4 flex items-center justify-between"><Link href="/" className="font-title font-semibold text-xl text-slate-800">Pathways Within <span className="text-wellness">Wellness</span></Link><ul className="hidden md:flex items-center gap-6 text-sm font-body"><li><Link href="/services" className="text-wellness font-medium">Services</Link></li><li><Link href="/about" className="text-slate-700 hover:text-wellness">About</Link></li><li><Link href="/contact" className="text-slate-700 hover:text-wellness">Contact</Link></li></ul><a href="https://pathwayswithinwellness.janeapp.com/" className="hidden sm:inline-block bg-wellness text-white text-sm px-4 py-2 rounded-lg font-title font-medium" target="_blank" rel="noopener noreferrer">Book Now</a></div></nav>
      <main id="main">
        <section className="bg-white py-16 md:py-20" aria-labelledby="page-title"><div className="max-w-site mx-auto px-6 lg:px-12"><nav className="text-sm text-slate-500 font-body mb-6" aria-label="Breadcrumb"><Link href="/services" className="hover:text-wellness">Services</Link><span className="mx-2">/</span><span className="text-slate-800">Teeth Whitening</span></nav><div className="max-w-3xl"><h1 id="page-title" className="font-title font-bold text-4xl md:text-5xl text-slate-800 mb-4">Teeth Whitening</h1><p className="text-xl text-slate-600 font-body">Brighten Your Smile Today</p></div></div></section>
        <section className="bg-ivory py-16"><div className="max-w-site mx-auto px-6 lg:px-12"><div className="max-w-3xl"><h2 className="font-title font-semibold text-2xl text-slate-800 mb-4">Professional Teeth Whitening</h2><p className="text-slate-600 font-body mb-4">Our professional teeth whitening treatment can brighten your smile up to 8 shades in just one session. Safe, fast, and effective—see dramatic results without sensitivity.</p></div></div></section>
        <section className="bg-white py-16"><div className="max-w-site mx-auto px-6 lg:px-12"><h2 className="font-title font-semibold text-2xl text-slate-800 mb-8 text-center">Benefits</h2><div className="grid md:grid-cols-3 gap-4 max-w-4xl mx-auto">{['Up to 8 Shades Brighter', 'Fast Results', 'Safe Treatment', 'No Sensitivity', 'Long-Lasting', 'Boosts Confidence'].map((item, i) => (<div key={i} className="bg-wellness/5 rounded-lg p-4 text-center border border-wellness/20"><span className="text-slate-700 font-body text-sm">{item}</span></div>))}</div></div></section>
        <section className="bg-wellness py-16"><div className="max-w-3xl mx-auto px-6 text-center"><h2 className="font-title font-bold text-3xl text-white mb-3">Ready for a Brighter Smile?</h2><p className="text-white/80 font-body mb-6">Book your teeth whitening appointment.</p><a href="tel:5163369209" className="inline-block bg-white text-wellness px-6 py-3 rounded-lg font-title font-medium">Call (516) 336-9209</a></div></section>
        <section className="bg-pearl py-12"><div className="max-w-site mx-auto px-6 lg:px-12"><h3 className="font-title font-medium text-lg text-slate-800 mb-4">Related Services</h3><div className="flex flex-wrap gap-2"><Link href="/services/facials-skincare" className="bg-white px-4 py-2 rounded-lg text-sm text-slate-700 font-body hover:bg-wellness/10 border border-slate-200">Facials</Link><Link href="/services" className="bg-wellness/10 px-4 py-2 rounded-lg text-sm text-wellness font-body hover:bg-wellness/20">View All →</Link></div></div></section>
      </main>
      <footer className="bg-chalkboard text-white py-12" role="contentinfo"><div className="max-w-site mx-auto px-6 lg:px-12 text-center text-sm text-slate-400">© {new Date().getFullYear()} Pathways Within Wellness. (516) 336-9209</div></footer>
    </>
  )
}

